# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20161118_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
