# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20161118_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Logins',
            new_name='Login',
        ),
    ]
